# Generated by Django 4.0.3 on 2022-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propiedades',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombrePropiedad', models.CharField(max_length=40, null=True)),
                ('tipoPropiedad', models.CharField(choices=[('Cas', 'Casa'), ('Dep', 'Departamento'), ('Vil', 'Villa'), ('Res', 'Residencia'), ('Ofi', 'Oficina'), ('Ter', 'Terreno'), ('Bod', 'Bodega'), ('Des', 'Desarrollo'), ('Edi', 'Edificio')], default='Cas', max_length=3)),
                ('tipOperacion', models.CharField(choices=[('V', 'Venta'), ('R', 'Renta')], default='V', max_length=1)),
                ('descripcion', models.TextField(max_length=2000)),
                ('ubicacion', models.CharField(max_length=35)),
                ('costo', models.SlugField(max_length=255)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('estacionamientos', models.IntegerField(default=0)),
                ('metrosTerreno', models.IntegerField(default=0)),
                ('metrosConstruccion', models.IntegerField(default=0)),
                ('pisos', models.IntegerField(blank=True)),
            ],
        ),
    ]
